# Generated by Django 4.2.6 on 2023-10-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='image',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
    ]
