# Generated by Django 4.2.6 on 2023-10-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_schools_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schools',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=32, verbose_name='First Name')),
                ('last_nam', models.CharField(max_length=64, verbose_name='Last Name')),
                ('date_of_birth', models.DateField()),
                ('phone', models.IntegerField()),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schools')),
            ],
        ),
    ]
