# Generated by Django 4.2.6 on 2023-10-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_schools_options_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
