# Generated by Django 4.2.6 on 2023-10-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='image',
            field=models.ImageField(blank=None, null=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
