# Generated by Django 4.2.6 on 2023-10-14 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_schools_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_nam',
            new_name='last_name',
        ),
    ]
